language: python
python:
    - "2.7_with_system_site_packages"

install:
    - "sudo apt-get -qq install build-essential python-dev tcllib"
    - "sudo apt-get -qq install blas lapack libblas-dev liblapack-dev"
    - "sudo apt-get -qq install python-cython python-numpy python-scipy python-matplotlib python-sphinx"
    - "sudo apt-get install suitesparse suitesparse-dev"
    - "pip install -r requirements.txt"

script: python unittests/test_all.py
branches:
  only:
    - v0.03

after_success:
    - coveralls