language: python
python:
    - "2.7_with_system_site_packages"

before_install:
    - "lsb_release -a"

install:
    - "sudo apt-get -qq install build-essential python-dev tcllib"
    - "sudo apt-get -qq install libblas-dev liblapack-dev"
    - "pip install -r requirements.txt"

script: python unittests/test_all.py
branches:
  only:
    - v0.03

after_success:
    - coveralls