language: python
sudo: false

python:
    - "2.7_with_system_site_packages"

addons:
  apt:
    packages:
    - build-essential
    - python-dev
    - python-setuptools
    - pythopn-numpy
    - tcllib
    - libblas-dev
    - liblapack-dev
    - libsuitesparse-dev
    - gfortran
    - g77

install:
    - "pip install scipy"
    - "pip install coveralls"
    - "pip install pylint"
    - "pip install -q cython"
    - "pip install -r requirements.txt"

script:
    - python -m unittests.TestAll
    - coverage run --source BioFlow -m unittests.TestAll

after_success:
    - coveralls
    - "pylint -d C -d import-error -d no-name-in-module -d no-member -d fixme -d too-few-public-methods -d no-init BioFlow"

notifications:
    email: false